---
title: "Client Report - What's in a Name? "
subtitle: "Course DS 250"
author: "Sebastian Berber"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
#| label: libraries
#| include: false
import pandas as pd
import numpy as np
import plotly.express as px
```


## Elevator pitch

_From the data that I was given, I was able to find some facinating inferences about the data. I was able to see that my name Sebastian started to become popular after the year 2000. I also wanted to see if there was any influence on the name Luke during the time that Star Wars was recently released. I found that the years after, the name did seem to become poplar._

```{python}
#| label: project data
#| code-summary: Read and format project data
# Include and execute your code here
df = pd.read_csv("https://github.com/byuidatascience/data4names/raw/master/data-raw/names_year/names_year.csv")
```


__Highlight the Questions and Tasks__

## QUESTION|TASK 1

__How does your name at your birth year compare to its use historically?__

_Historically speaking, The name sebastian dropped after the year 2002 but later peaked again in 2006 and continued to have an increase in frequency the following years. The name seemed to start to become popular after the year 2000._

```{python}
#| label: Q1
#| code-summary: Read and format data
# Include and execute your code here
data_sebastian = df.query("name == 'Sebastian'")

fig = px.bar(data_sebastian,
    x = "year",
    y = "Total",
    title = "Babies Named Sebastian by Year")

fig.update_xaxes(range=[1970, 2016],
                 title_text='Year (1970-2015)')
fig.update_yaxes(title_text='Frequency')

fig.update_layout(
    shapes=[
        dict(
            type='line',
            x0=2002,
            x1=2002,
            y0=10000,
            y1=max(data_sebastian['AK']),  # Adjust the y-coordinate range as needed
            line=dict(color='red', width=2)
        )
    ]
)

fig.update_layout(
    annotations=[
        dict(
            x=1995,  # X-coordinate of the annotation
            y=9000,  # Y-coordinate of the annotation
            text='Year I was born (2002)',
            showarrow=False
        )
    ]
)


```


## QUESTION|TASK 2

__If you talked to someone named Brittany on the phone, what is your guess of his or her age? What ages would you not guess?__

_Well from the look of the graph, The name Brittany peaked in the year 1990 and it had 32,000 babies named Brittany that year. So I would guess that her age would've been 34. I would not guess her age to be 40 or older neither 25 or younger becuase those would be the ages of when Brittany was starting to become popular and when the name was starting to become less popular._

```{python}
#| label: Q2
#| code-summary: Read and format data
# Include and execute your code here
data_brittany = df.query("name == 'Brittany'") 

fig = px.bar(data_brittany,
    x = "year",
    y = "Total",
    title = "Babies named Brittany by Birth Year")

fig.update_xaxes(range=[1970, 2016],
                 title_text='Year (1970-2015)')
fig.update_yaxes(title_text='Frequency')

fig.show()

```


## QUESTION|TASK 3

__Mary, Martha, Peter, and Paul are all Christian names. From 1920 - 2000, compare the name usage of each of the four names. What trends do you notice?__

_Well, from the graph, I can tell that the name trends became popular between 1940 and 1960. Mary had a huge portion of the trend but they all peacked between those times._

```{python}
#| label: Q3
#| code-summary: Read and format data
# Include and execute your code here
selected_names = ['Mary', 'Martha', 'Peter', 'Paul']
filtered_df = df[(df['name'].isin(selected_names))]

filtered_df1 = px.bar(filtered_df,
    x = "year",
    y = "Total",
    color = "name",
    title = "Chistian Names By Year")

filtered_df1.update_xaxes(range=[1920, 2000],
                          title = "Year (1920-2000)")

filtered_df1.update_yaxes(title = "Frequency")

filtered_df1
```

## QUESTION|TASK 4

__Think of a unique name from a famous movie. Plot the usage of that name and see how changes line up with the movie release. Does it look like the movie had an effect on usage?__

_I waned to see how the name Luke increased after the Star Wars Saga was introduced. Star Wars is arguably one of the most famous movie series that has ever come out. Below shows the trend of the name and the lines are the release years of the 3 movies._

```{python}
#| label: Q4
#| code-summary: Read and format data
# Include and execute your code here

name_luke = df.query("name == 'Luke'")

fig = px.bar(name_luke,
    x = "year",
    y = "Total",
    title = "Is The Name Luke Related to Star Wars")


fig.update_xaxes(range=[1975, 2015],
                 title = "Year (1975-2015)")
fig.update_yaxes(title = "Frequency")
fig.update_layout(
    shapes=[
        dict(
            type='line',
            yref='paper',
            y0=0,
            y1=1,
            xref='x',
            x0='1977',
            x1='1977',
            line=dict(color='yellow'),
        ),
        dict(
            type='line',
            yref='paper',
            y0=0,
            y1=1,
            xref='x',
            x0='1980',
            x1='1980',
            line=dict(color='red'),
        ),
        dict(
            type='line',
            yref='paper',
            y0=0,
            y1=1,
            xref='x',
            x0='1983',
            x1='1983',
            line=dict(color='green'),
        )
    ],
)

fig.show()
```

