---
title: "Sebastian Berber Resume"
subtitle: "Sebastian Berber Portfolio"
# use quarto markdown to 
---

## Objective 

Highly motivated and skilled individual with a diverse work history, seeking employment to save money for college.
Experienced in various roles, including irrigation repair, customer service, technical support, and food delivery.
Committed to providing exceptional service, demonstrating a strong work ethic, and achieving customer
satisfaction

## Skills
    • Strong problem-solving and analytical abilities.
    • Excellent customer service and communication skills.
    • Proficient in computer repair and maintenance.
    • Bilingual fluency in English and Spanish (written and spoken).
    • Efficient and dependable, delivering results in a timely manner.
    • Ability to work independently and as part of a team

## Education:
    • High School Diploma (year graduated: 2020)
      Liberty Hill High School, Liberty Hill, Texas
    • Bachelor's Degree in Data Science (expected completion: 2027)
      Brigham Young University-Idaho, Rexburg, Idaho

# Work Experience

## Pressure Washing Technician, Binney and the Jets [Liberty Hill, Texas] May 2023 - Present
    • Successfully pressure washed commercial vehicles and waste receptacles, maintaining their cleanliness
      and appearance.
    • Operated company truck, pulling the water tank and pressure washing trailer, ensuring efficient
      completion of tasks.
    • Conducted equipment maintenance and repairs to maximize performance and minimize downtime.
## Volunteer Service, [States: Massachusetts, Connecticut, Rhode Island] April 2021 - May 2023
    • Engaged directly with the public through social media and face-to-face meetings.
    • Taught English speaking classes to non-English speakers, sharing language skills and promoting education.
    • Volunteered at food banks and soup kitchens, serving the community in need.
    • Served as a trainer for new missionaries and District Leader, providing training and guidance to other
      missionaries.
## Independent Contractor, Door Dash, [Austin, Texas] April 2021 - May 2023
    • Delivered food orders promptly, providing excellent customer service and achieving substantial tips.
    • Demonstrated adaptability and efficiency in a fast-paced, customer-focused environment.
    • Maintained professionalism and ensured customer satisfaction.
## Food Service Team Member, Whataburger, [Cedar Park, Texas] April 2020 - March 2021
    • Took customer food orders with accuracy and efficiency.
    • Demonstrated versatility by excelling in working at various food prep stations.
    • Maintained cleanliness and organization in work areas to meet quality standards.
    • Consistently delivered exceptional customer service, ensuring customer satisfaction and fostering positive
      interactions and a positive dining experience.
    • Received positive feedback from the employer for being dependable, hardworking, and displaying a
      positive attitude.
    • Collaborated with team members to ensure smooth workflow and efficient operations.
## Computer Technician Intern, PraxiTek LLC [Cedar Park, Texas] March 2020 - April 2020
    • Assisted senior technician in stripping, disassembling, and disposing of old computers.
    • Conducted hard drive data sanitization and basic PC repairs under supervision.
    • Participated in CAT 6 cable installation and performed basic equipment maintenance tasks.
## Irrigation Repair Technician, OnDemand Sprinklers [Liberty Hill, Texas] June 2019 - August 2019
    • Conducted pipe and sprinkler repairs, ensuring efficient and effective irrigation systems.
    • Programmed sprinkler systems to meet specific client requirements and optimize water usage.
    • Successfully couriered parts for management and other teams, ensuring seamless operations.
    • Demonstrated professionalism and courtesy when interacting with customers, providing excellent service.
    • Received consistent feedback from employer highlighting my speed, efficiency, and dep

[MarkDown Basics](https://quarto.org/docs/authoring/markdown-basics.html#links-images)

